version: '3.1'

services: 
  sispac-app:
    build: .
    ports: 
      - 8080:80
    volumes:
      - ./:/usr/share/nginx
    networks: 
      - sispac-network

  mysql-app:
    image: mysql:5.7.22
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: sispac
      MYSQL_DATABASE: sispac
      MYSQL_ROOT_HOST: '%'
    networks: 
      - sispac-network

networks: 
  sispac-network:
    driver: bridge